# image will be published to ghcr.io/<user>/<name>
name: ublue-nvidia-virt
# description will be included in the image's metadata
description: Universal Blue with Nvidia and libvirt installed

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - libvirt
      - virt-manager
      - rclone
      - kgpg
      - python3-pip
      - btop
      - intel-media-driver
      - neofetch
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
        install:
      - com.github.Eloston.UngoogledChromium
      - com.github.tchx84.Flatseal
      - com.vivaldi.Vivaldi
      - io.mpv.Mpv
      - org.kde.kontact
      - org.kde.yakuake
      - org.strawberrymusicplayer.strawberry
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
    remove:
        # - org.gnome.eog
    user:
     install:
      - com.bitwarden.desktop
      - com.discordapp.Discord
      - io.freetubeapp.FreeTube
      - io.github.mimbrero.WhatsAppDesktop
      - org.kde.tokodon
      - org.musicbrainz.Picard
      - org.signal.Signal
     remove:

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
